# Generated by Django 4.2.3 on 2023-09-22 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_created_by_alter_task_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
